resolver: lts-14.1

packages:
- .

extra-deps:
- jsaddle-0.9.6.0
- jsaddle-warp-0.9.6.0
- ref-tf-0.4.0.1
- stm-containers-1.1.0.4
- stm-hamt-1.2.0.2
- focus-1.0.1.3
- primitive-extras-0.7.1


flags:
  miso:
    jsaddle: true